import type { INodeProperties } from 'n8n-workflow';
import { leadTagsProperty } from './shared';

export const leadDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['lead'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a lead' },
			{ name: 'Delete', value: 'delete', action: 'Delete a lead' },
			{ name: 'Get', value: 'get', action: 'Get a lead' },
			{ name: 'Update', value: 'update', action: 'Update a lead' },
		],
		default: 'create',
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@example.com',
		displayOptions: { show: { resource: ['lead'], operation: ['create'] } },
		default: '',
		required: true,
		description: 'Email address of the lead',
	},
	{
		displayName: 'Subscribed',
		name: 'subscribed',
		type: 'boolean',
		displayOptions: { show: { resource: ['lead'], operation: ['create'] } },
		default: true,
		description: 'Whether the lead is subscribed to marketing emails',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['lead'], operation: ['create'] } },
		options: [
			{
				displayName: 'Double Opt-In',
				name: 'doubleOptIn',
				type: 'boolean',
				default: false,
				description: 'Whether to send the configured double opt-in confirmation email',
			},
			{ displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
			{ displayName: 'IP Address', name: 'ipAddress', type: 'string', default: '' },
			{ displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
			{
				displayName: 'Custom Fields (JSON)',
				name: 'fields',
				type: 'json',
				default: '{}',
				description: 'Custom field merge-tag/value pairs',
			},
			{
				displayName: 'Meta (JSON)',
				name: 'meta',
				type: 'json',
				default: '{}',
				description: 'Lead metadata such as company and role',
			},
			{
				displayName: 'Override Existing',
				name: 'overrideExisting',
				type: 'boolean',
				default: false,
				description: 'Whether to update an existing lead when the email already exists',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'America/Toronto',
			},
		],
	},
	{
		...leadTagsProperty,
		displayOptions: { show: { resource: ['lead'], operation: ['create'] } },
	},
	{
		displayName: 'Email or Lead Hash',
		name: 'leadIdentifier',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['lead'], operation: ['get', 'update', 'delete'] },
		},
		description: 'Lead email address or its MD5 hash; email addresses are hashed automatically',
	},
	{
		displayName: 'Fields to Update',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['lead'], operation: ['update'] } },
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '' },
			{ displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
			{ displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: '' },
			{ displayName: 'IP Address', name: 'ipAddress', type: 'string', default: '' },
			{ displayName: 'Subscribed', name: 'subscribed', type: 'boolean', default: true },
			{ displayName: 'Custom Fields (JSON)', name: 'fields', type: 'json', default: '{}' },
			{ displayName: 'Meta (JSON)', name: 'meta', type: 'json', default: '{}' },
			{
				displayName: 'Add Tags (JSON)',
				name: 'addTags',
				type: 'json',
				default: '[]',
				description: 'JSON array of tags to add',
			},
			{
				displayName: 'Remove Tags (JSON)',
				name: 'removeTags',
				type: 'json',
				default: '[]',
				description: 'JSON array of tags to remove',
			},
		],
	},
];
