import type { INodeProperties } from 'n8n-workflow';
import { orderItemsProperty, paginationProperties } from './shared';

export const orderDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['order'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create an order' },
			{ name: 'Delete', value: 'delete', action: 'Delete an order' },
			{ name: 'Get', value: 'get', action: 'Get an order' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many orders' },
			{ name: 'Update', value: 'update', action: 'Update an order' },
		],
		default: 'getAll',
	},
	{
		displayName: 'Order ID',
		name: 'orderId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['order'],
				operation: ['create', 'get', 'update', 'delete'],
			},
		},
	},
	{
		displayName: 'Customer Email',
		name: 'customerEmail',
		type: 'string',
		placeholder: 'name@example.com',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: 'USD',
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
		description: 'Three-letter currency code such as USD or CAD',
	},
	{
		displayName: 'Total Price',
		name: 'totalPrice',
		type: 'number',
		default: 0,
		required: true,
		typeOptions: { minValue: 0 },
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
	},
	{
		...orderItemsProperty,
		required: true,
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
	},
	{
		displayName: 'Customer Options',
		name: 'customerOptions',
		type: 'collection',
		placeholder: 'Add Customer Field',
		default: {},
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
		options: [
			{ displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
			{ displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
			{ displayName: 'Subscribed', name: 'subscribed', type: 'boolean', default: true },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: '' },
			{ displayName: 'IP Address', name: 'ipAddress', type: 'string', default: '' },
			{ displayName: 'Custom Fields (JSON)', name: 'fields', type: 'json', default: '{}' },
			{ displayName: 'Meta (JSON)', name: 'meta', type: 'json', default: '{}' },
			{
				displayName: 'Tags (JSON)',
				name: 'tags',
				type: 'json',
				default: '[]',
				description: 'JSON array of customer tags',
			},
		],
	},
	{
		displayName: 'Order Options',
		name: 'orderOptions',
		type: 'collection',
		placeholder: 'Add Order Field',
		default: {},
		displayOptions: { show: { resource: ['order'], operation: ['create'] } },
		options: [
			{
				displayName: 'Campaign ID',
				name: 'campaignId',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 1, numberStepSize: 1 },
			},
		],
	},
	{
		displayName: 'Fields to Update',
		name: 'orderUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['order'], operation: ['update'] } },
		options: [
			{
				displayName: 'Campaign ID',
				name: 'campaignId',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 1, numberStepSize: 1 },
			},
			{ displayName: 'Currency', name: 'currency', type: 'string', default: '' },
			{
				displayName: 'Customer (JSON)',
				name: 'customer',
				type: 'json',
				default: '{}',
				description: 'Customer fields accepted by the MailBluster order API',
			},
			{
				displayName: 'Items (JSON)',
				name: 'items',
				type: 'json',
				default: '[]',
				description: 'JSON array of order items',
			},
			{ displayName: 'Total Price', name: 'totalPrice', type: 'number', default: 0 },
		],
	},
	...paginationProperties.map((property) => ({
		...property,
		displayOptions: {
			...property.displayOptions,
			show: {
				resource: ['order'],
				operation: ['getAll'],
				...(property.displayOptions?.show ?? {}),
			},
		},
	})),
];
